source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'unicorn'
gem 'unicorn-worker-killer'
gem 'slim'
gem 'geocoder'
gem 'yelp'
gem 'google_places'
gem 'mongoid', '~> 4.0.0'
